-- AlterTable
ALTER TABLE "Absence" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endDate" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "TimeEntry" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(3);
